### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by Lzsh1** [fgvsuiye/autojs6#4]
Version: 2223
Android: 34
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2750)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2461)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1752)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14109)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:12816)

java.lang.RuntimeException:Unable to create service org.autojs.autojs.core.image.capture.ScreenCapturerForegroundService: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{279b105 8334:org.autojs.autojs6/u0a353} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
android.app.ActivityThread.handleCreateService(ActivityThread.java:4962)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2750)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2461)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1752)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14109)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:12816)

**Comment by fgvsuiye** [comment]
给权限。
